### ISSUE TITLE
Cannot connect ioPay to the staking portal

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-desktop-wallet#1986]
It could be the expired certificate issue that already happened in the past.

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/11096047/201535098-f92a61b7-72e7-4ff4-9d70-d29842ecc9b1.png">

**Comment by guo** [comment]
If I open from terminal, iotex desktop wallet connects to stake.iotex.io well.  FYI.

**Comment by simonerom** [comment]
@guo Solution worked for me (and seems to fix the problem forever, even if I run from the UI).

However, before it was fixed, I was getting the same error in Safari:

![6ac5c2ea-89be-4027-901b-3f1abf10166a](https://user-images.githubusercontent.com/11096047/201536029-d4c5f757-a753-43c3-b519-09d920c69584.jpeg)


When I clicked on the `wss://... `link displayed in the log, it triggered the browser "Unsecure website" warning with the certificate details button.
The details about the certificate say it expired on Oct 15:

![BSKudzb3bH](https://user-images.githubusercontent.com/11096047/201536110-a5f1ba10-e98d-4002-bcfe-b1639e0676c0.jpg)

**Comment by uu-z** [comment]
we have forced refresh the certificate, and it works for me. could you please try it again @simonerom

**Comment by sshanmugam** [comment]
I tried opening from terminal and still having the same issue. (wallet version - 1.0.26)
(base) ➜  MacOS ./IoTeX\ Desktop\ Wallet 

![Screen Shot 2022-12-02 at 7 46 34 AM](https://user-images.githubusercontent.com/2058137/205296282-b0250244-6d08-49e5-a41f-3b36be25d4b1.png)

I also tried finding the local.iotex.io cert in Root X1, I don't find any. Any thoughts what am missing?

**Comment by sshanmugam** [comment]
No, I don't use VPN.

**Comment by jrynkiew** [comment]
> No, I don't use VPN.

You could try using a different internet connection, like a mobile hotspot.

**Comment by guo** [comment]
@sshanmugam  which website are you visiting? 
Thanks!

**Comment by sshanmugam** [comment]
@guo I am using https://stake.iotex.io/my-votes.

**Comment by ronyas** [comment]
I am experiencing the same issue, failed connecting the staking protal to my desktop wallet ver 1.10. basically nothing happens after clicking on the Connect button. I've tried a few browsers but none of them worked. appreciate a fix asap.

**Comment by jrynkiew** [comment]
> I am experiencing the same issue, failed connecting the staking protal to my desktop wallet ver 1.10. basically nothing happens after clicking on the Connect button. I've tried a few browsers but none of them worked. appreciate a fix asap.

Please try the newest version of the ioPay desktop app. If you're using ioPay desktop on Linux, 1.0.16 should be stable, but the newer versions should work as well.
